create table if not exists public.participation_events (
    id bigint generated by default as identity primary key,
    session_id uuid not null,
    name text not null check (char_length(name) between 2 and 30),
    status text not null check (status in ('registered', 'completed', 'abandoned')),
    question_number integer not null default 0 check (question_number between 0 and 10),
    created_at timestamptz not null default now()
);

alter table public.participation_events enable row level security;

drop policy if exists "Anyone can record participation" on public.participation_events;
create policy "Anyone can record participation"
    on public.participation_events for insert
    to anon
    with check (true);

drop policy if exists "Anyone can read participation" on public.participation_events;
create policy "Anyone can read participation"
    on public.participation_events for select
    to anon
    using (true);
