create table public.ranking (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 2 and 30),
    points integer not null check (points between 0 and 100),
    correct integer not null check (correct between 0 and 10),
    created_at timestamptz not null default now()
);

alter table public.ranking enable row level security;

create policy "Anyone can read ranking"
    on public.ranking for select
    to anon
    using (true);

create policy "Anyone can submit ranking"
    on public.ranking for insert
    to anon
    with check (true);